#!/usr/bin/env python3
"""Generate the owned byte scanf leaf from pinned musl 1.2.6, never at build time."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys
import tempfile

sys.dont_write_bytecode = True
from generate_owned_printf_float import generation_environment
from generate_libc_math_long_double_completion import (
    ROOT, EXPECTED_MUSL_TREE_DIGEST, normalized_tree_digest, checked_compiler, COMPILE_FLAGS,
)

SOURCES = ("src/internal/shgetc.h", "src/internal/shgetc.c", "src/internal/intscan.c",
    "src/internal/floatscan.c", "src/stdio/vfscanf.c")

ADAPTER = r"""
#include <stdlib.h>
#include <stdarg.h>
#include <ctype.h>
#include <limits.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include <math.h>
#include <float.h>
#include <errno.h>
typedef long off_t;
#define EOF (-1)
#define FLOCK(f) ((void)0)
#define FUNLOCK(f) ((void)0)
/* Only scanner-private fields. This is never the public opaque FILE. */
typedef struct {
    unsigned char *rpos, *rend, *buf, *shend;
    off_t shlim, shcnt;
    void *context;
    int (*get)(void *);
} FILE;
static int __toread(FILE *f) { return 0; }
static int __uflow(FILE *f)
{
    int byte = f->get(f->context);
    if (byte < 0) return EOF;
    f->buf[0] = byte;
    f->rpos = f->rend = f->buf + 1;
    return byte;
}
"""

ENTRY = r"""
__attribute__((visibility("hidden")))
int __crabc_owned_scan(void *context, int (*get)(void *), void (*unget)(void *, int),
    const char *format, va_list *arguments)
{
    /* pok=0 in scanf needs only one restored byte. Eight preceding bytes
     * preserve shgetc's upstream UNGET pointer-arithmetic allowance. */
    unsigned char storage[9] = {0};
    FILE cursor = {.rpos=storage+8, .rend=storage+8, .buf=storage+8,
        .context=context, .get=get};
    int result = vfscanf(&cursor, format, *arguments);
    if (cursor.rpos < cursor.rend) unget(context, *cursor.rpos);
    return result;
}
"""


def translation(source_root):
    sources = {name: (source_root / name).read_text() for name in SOURCES}
    sh = sources[SOURCES[0]]
    sh = sh[sh.index("#define shcnt"):sh.index("#define sh_fromstring")]
    bodies = []
    for name in SOURCES[1:]:
        body = re.sub(r"^#include[^\n]*\n", "", sources[name], flags=re.MULTILINE)
        if name.endswith("vfscanf.c"):
            body = body[:body.index("weak_alias(")]
            body = body.replace("\tmbstate_t st;\n", "").replace("\twchar_t wc;\n", "")
            begin = body.index("\t\t\tif (size == SIZE_l) {")
            end = body.index("\t\t\t} else if (alloc) {", begin)
            body = body[:begin] + "\t\t\tif (alloc) {" + body[end+len("\t\t\t} else if (alloc) {"):]
            point = body.index("\n\t\tswitch (t) {")
            body = body[:point] + "\n\t\tif (size == SIZE_l && (t=='c' || t=='s' || t=='[')) { errno=EINVAL; goto fmt_fail; }\n" + body[point:]
        bodies.append(body)
    source = ADAPTER + sh + "\n".join(bodies) + ENTRY
    # Every helper stays private to this leaf, independently of the strto*
    # scanner's deliberately narrower private callback contract.
    for name in ("__shlim", "__shgetc", "__intscan", "__floatscan", "vfscanf",
        "scanexp", "decfloat", "hexfloat", "store_int", "arg_n", "__toread", "__uflow"):
        source = re.sub(r"\b" + name + r"\b", "crabc_owned_scan_" + name.lstrip("_"), source)
    return source, sources


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--musl-source", required=True, type=Path)
    parser.add_argument("--cc", default="/usr/local/bin/crabc-x86_64-musl-gcc")
    parser.add_argument("--output", type=Path,
        default=ROOT / "libc/src/c_abi/x86_64/owned_scanf_musl_x86_64.S")
    args = parser.parse_args()
    source_root = args.musl_source.resolve()
    if normalized_tree_digest(source_root) != EXPECTED_MUSL_TREE_DIGEST:
        raise SystemExit("pinned musl tree digest mismatch")
    environment = generation_environment()
    compiler = checked_compiler(args.cc, environment=environment)
    source, sources = translation(source_root)
    with tempfile.TemporaryDirectory(prefix="owned-scanf.", dir=environment["TMPDIR"]) as temporary:
        unit, assembly = Path(temporary) / "scan.c", Path(temporary) / "scan.S"
        unit.write_text(source)
        subprocess.run([compiler, *COMPILE_FLAGS, "-fPIC", "-fvisibility=hidden", "-S", str(unit), "-o", str(assembly)],
            check=True, env=environment)
        text = assembly.read_text()
    text = re.sub(r"(?<![A-Za-z0-9_.])\.L([A-Za-z0-9_.$]+)", r".Lcrabc_owned_scan_\1", text)
    text = re.sub(r"^\s*\.(file|ident)\s+.*\n", "", text, flags=re.MULTILINE)
    notice = (source_root / "COPYRIGHT").read_text().split("Authors/contributors include:")[0]
    header = "/*\nGenerated by compat/x86_64/generate_owned_scanf.py from musl 1.2.6.\n"
    header += "See owned_scanf.rs for source mapping, callback and byte-only differences.\n"
    for name, contents in sources.items():
        header += name + " SHA256: " + hashlib.sha256(contents.encode()).hexdigest() + "\n"
    header += "Translation SHA256: " + hashlib.sha256(source.encode()).hexdigest() + "\n\n"
    args.output.write_text(header + notice + "\n*/\n" + text)


if __name__ == "__main__":
    main()
