#!/usr/bin/env python3
"""Generate owned x87 printf numerics from the digest-checked musl 1.2.6 tree.

Not invoked by the product build. Shares the established pinned GCC/source
validator and flags; only the FILE output adapters and ABI entry are local.
"""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import tempfile

from generate_libc_math_long_double_completion import (
    ROOT, EXPECTED_MUSL_TREE_DIGEST, normalized_tree_digest,
    checked_compiler, compiler_environment, COMPILE_FLAGS,
)

ADAPTER = r"""
#include <stdint.h>
#include <stddef.h>
#include <limits.h>
#include <float.h>
#include <math.h>
#include <string.h>
typedef struct {
    void *state;
    void (*bytes)(void *, const char *, size_t);
    void (*repeat)(void *, int, size_t);
} FILE;
enum { BIGLPRE = 5 };
static void out(FILE *f, const char *s, size_t n) { f->bytes(f->state, s, n); }
/* vfprintf.c pad's admission rule, with repeated bytes delegated directly
 * to the counting/truncating/stream sink instead of a local 256-byte loop. */
static void pad(FILE *f, char c, int w, int l, int fl)
{
    if (fl & (LEFT_ADJ | ZERO_PAD) || l >= w) return;
    f->repeat(f->state, c, (size_t)(w-l));
}
"""
ENTRY = r"""
/* Rust has no C binary80 value type. All ten meaningful bytes cross by
 * address, never via a binary64 narrowing or a binary128 ABI surrogate. */
__attribute__((visibility("hidden")))
void __crabc_owned_printf_promote(double value, void *destination)
{
    long double promoted = value;
    memcpy(destination, &promoted, 10);
}
__attribute__((visibility("hidden")))
int __crabc_owned_printf_float(FILE *sink, const void *value,
    int width, int precision, int flags, int specifier, int long_precision)
{
    long double number;
    memcpy(&number, value, 10);
    return fmt_fp(sink, number, width, precision, flags, specifier,
        long_precision ? BIGLPRE : 0);
}
"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--musl-source", required=True, type=Path)
    parser.add_argument("--cc", default="/usr/local/bin/crabc-x86_64-musl-gcc")
    parser.add_argument("--output", type=Path,
        default=ROOT / "libc/src/c_abi/x86_64/owned_printf_float_musl_x86_64.S")
    args = parser.parse_args()
    source_root = args.musl_source.resolve()
    if normalized_tree_digest(source_root) != EXPECTED_MUSL_TREE_DIGEST:
        raise SystemExit("pinned musl tree digest mismatch")
    compiler = checked_compiler(args.cc)
    original = (source_root / "src/stdio/vfprintf.c").read_text()
    macros = original[original.index("#define MAX"):original.index("/* State machine")]
    numeric = original[original.index("static const char xdigits"):original.index("static int getint")]
    # fmt_fp, fmt_u and xdigits are copied verbatim. Unused fmt_x/fmt_o from
    # the contiguous upstream block are eliminated by the pinned compiler.
    includes, adapter = ADAPTER.split("typedef struct", 1)
    source = includes + macros + "typedef struct" + adapter + numeric + ENTRY
    with tempfile.TemporaryDirectory(prefix="owned-printf-float.") as temporary:
        unit = Path(temporary) / "owned_printf_float.c"
        assembly = Path(temporary) / "owned_printf_float.s"
        unit.write_text(source)
        # Unlike the existing arithmetic-only leaves, fmt_fp addresses string
        # literals. Use PC-relative PIC addressing for the owned static-PIE
        # product as well as ET_EXEC; numerical optimization flags are shared.
        subprocess.run([compiler, *COMPILE_FLAGS, "-fPIC", "-S", str(unit), "-o", str(assembly)],
            check=True, env=compiler_environment())
        text = assembly.read_text()
    text = re.sub(r"(?<![A-Za-z0-9_.])\.L([A-Za-z0-9_.$]+)",
        r".Lcrabc_owned_printf_float_\1", text)
    text = re.sub(r"^\s*\.(file|ident)\s+.*\n", "", text, flags=re.MULTILINE)
    notice = (source_root / "COPYRIGHT").read_text().split("Authors/contributors include:")[0]
    header = "/*\nGenerated by compat/x86_64/generate_owned_printf_float.py.\n"
    header += "musl 1.2.6 src/stdio/vfprintf.c (fmt_fp/fmt_u/xdigits), unchanged numeric algorithm.\n"
    header += "Source SHA256: " + hashlib.sha256(original.encode()).hexdigest() + "\n"
    header += "Generated translation-unit SHA256: " + hashlib.sha256(source.encode()).hexdigest() + "\n"
    header += "See owned_printf_float.rs for ABI, adapter differences and provenance.\n\n" + notice + "\n*/\n"
    args.output.write_text(header + text)


if __name__ == "__main__":
    main()
